codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      frontend:
        target: 80%
        flags: [frontend]
      rust:
        target: 70%
        flags: [rust]
    patch:
      default:
        target: 80%

flags:
  frontend:
    paths:
      - src/
    carryforward: true
  rust:
    paths:
      - src-tauri/src/
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
